version: "3.9"

services:
  automate-node:
    build: .
    image: automate-node:latest
    devices:  
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: unless-stopped
