version: "3.9"

services:
  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - ./data:/var/lib/redis-stack
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-stack-server /usr/local/etc/redis/redis.conf
